# Generated by Django 4.2 on 2023-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product_price_product_vendor_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
