# Generated by Django 4.2 on 2023-04-15 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator("0.01")],
            ),
        ),
    ]
