# Generated by Django 4.2 on 2023-04-15 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_product",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
