# Generated by Django 4.2 on 2023-04-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_product_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="customer",),
    ]
