# Generated by Django 4.2 on 2023-04-17 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0008_product_imageurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=50)),
                ("vendor", models.CharField(default="Unknown", max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("imageUrl", models.CharField(default="", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_product",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
